## Esercizi sui Numpy array  5 Marzo 2024


**Esercizio 1**

Confrontare il tempo di esecuzione dei due metodi per la creazione di un numpy array di 2000000 di elementi equidistanti nell'intervallo [-4,4]:

    1) costruzione con utilizzo di np.linspace
    
    2) Assegnazione manuale dei valori nel ciclo.
    

In [1]:
import numpy as np
print(np.linspace(-4, 4, num=2000000))
# lng = np.array([])
# i = -4
# while i < 4:
#    i = i + (1 / 2000000)
#    np.append(lng, i)
# print(lng)

[-4.       -3.999996 -3.999992 ...  3.999992  3.999996  4.      ]


**Esercizio 2**

-     Creare un numpy array 1D (chiamato c) di valori equidistanti tra 7 e 41 con step 2.

-      Trasformare l'array c in un numpy array 2d (chiamato c1) con shape (2,9) usando il metodo .reshape((m,n))

-       Determinare se c1 e' una copia o una vista dell'originale.

In [2]:
import numpy as np
c = np.arange(7, 42, 2)
c1 = c.reshape((2, 9))
print(c1, c)
c1[0] = np.zeros((1, 9))
print(c1, c)
print("E' una view, dato che se modifico c1 si modifica anche c")

[[ 7  9 11 13 15 17 19 21 23]
 [25 27 29 31 33 35 37 39 41]] [ 7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41]
[[ 0  0  0  0  0  0  0  0  0]
 [25 27 29 31 33 35 37 39 41]] [ 0  0  0  0  0  0  0  0  0 25 27 29 31 33 35 37 39 41]
E' una view, dato che se modifico c1 si modifica anche c


**Esercizio 3**

-     Costruire un numpy array 1d, denominato $C$ di valori che variano tra 15 e 41 con step 2

-     Trasformarlo in un numpy array 2d con shape(7,2) usando il metodo . resize(7,2)  che lavora in-place,  (cioè  modifica l'array esistente, non è necessario creare una copia). Verificare la shape di C e dire se C è copia o vista?

In [3]:
C = np.arange(15, 42, 2)
C1 = np.resize(C, (7, 2))
print(C, C1)
print("View" if np.shares_memory(C, C1) else "Copia")

[15 17 19 21 23 25 27 29 31 33 35 37 39 41] [[15 17]
 [19 21]
 [23 25]
 [27 29]
 [31 33]
 [35 37]
 [39 41]]
Copia


**Esercizio 4**

-      Costruire il numpy array  s  formato da 100 valori equidistanti in  [0,4],

-      considerarne il reshape in un array 2d che ha 4 righe con un numero opportuno di colonne

In [4]:
s = np.linspace(0, 4, 100)
sView = s.reshape((4, int(100/4)))
print(sView)

[[0.         0.04040404 0.08080808 0.12121212 0.16161616 0.2020202
  0.24242424 0.28282828 0.32323232 0.36363636 0.4040404  0.44444444
  0.48484848 0.52525253 0.56565657 0.60606061 0.64646465 0.68686869
  0.72727273 0.76767677 0.80808081 0.84848485 0.88888889 0.92929293
  0.96969697]
 [1.01010101 1.05050505 1.09090909 1.13131313 1.17171717 1.21212121
  1.25252525 1.29292929 1.33333333 1.37373737 1.41414141 1.45454545
  1.49494949 1.53535354 1.57575758 1.61616162 1.65656566 1.6969697
  1.73737374 1.77777778 1.81818182 1.85858586 1.8989899  1.93939394
  1.97979798]
 [2.02020202 2.06060606 2.1010101  2.14141414 2.18181818 2.22222222
  2.26262626 2.3030303  2.34343434 2.38383838 2.42424242 2.46464646
  2.50505051 2.54545455 2.58585859 2.62626263 2.66666667 2.70707071
  2.74747475 2.78787879 2.82828283 2.86868687 2.90909091 2.94949495
  2.98989899]
 [3.03030303 3.07070707 3.11111111 3.15151515 3.19191919 3.23232323
  3.27272727 3.31313131 3.35353535 3.39393939 3.43434343 3.47474747
  3.5151

**Esercizio 5**

-     Costruire il numpy array s formato da 100 valori equidistanti in  [0,4]
-     considerarne il reshape in un array 2d che ha 4 colonne con un numero opportuno di righe

In [5]:
s = np.linspace(0, 4, 100)
sView = s.reshape((25, 4))
print(sView)

[[0.         0.04040404 0.08080808 0.12121212]
 [0.16161616 0.2020202  0.24242424 0.28282828]
 [0.32323232 0.36363636 0.4040404  0.44444444]
 [0.48484848 0.52525253 0.56565657 0.60606061]
 [0.64646465 0.68686869 0.72727273 0.76767677]
 [0.80808081 0.84848485 0.88888889 0.92929293]
 [0.96969697 1.01010101 1.05050505 1.09090909]
 [1.13131313 1.17171717 1.21212121 1.25252525]
 [1.29292929 1.33333333 1.37373737 1.41414141]
 [1.45454545 1.49494949 1.53535354 1.57575758]
 [1.61616162 1.65656566 1.6969697  1.73737374]
 [1.77777778 1.81818182 1.85858586 1.8989899 ]
 [1.93939394 1.97979798 2.02020202 2.06060606]
 [2.1010101  2.14141414 2.18181818 2.22222222]
 [2.26262626 2.3030303  2.34343434 2.38383838]
 [2.42424242 2.46464646 2.50505051 2.54545455]
 [2.58585859 2.62626263 2.66666667 2.70707071]
 [2.74747475 2.78787879 2.82828283 2.86868687]
 [2.90909091 2.94949495 2.98989899 3.03030303]
 [3.07070707 3.11111111 3.15151515 3.19191919]
 [3.23232323 3.27272727 3.31313131 3.35353535]
 [3.39393939 

**Esercizio 6**  

-     Scrivere il numpy  array 2d, A, [[10,11,12],[13,14,15],[16,17,18]] 
-     trasformarlo in un numpy array 1d usando il metodo .ravel()  
-     Si tratta di una copia o di una vista?

In [6]:
A = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
ravel = A.ravel()
print(ravel)
print("View" if np.shares_memory(A,ravel) else "Copy")

[10 11 12 13 14 15 16 17 18]
View


**Esercizio 7**  

-     Scrivere il numpy  array 2d, A, [[10,11,12],[13,14,15],[16,17,18]] 
-     trasformarlo in un numpy array 1d usando il metodo  .flatten().
-     Si tratta di una copia o di una vista?

In [7]:
flat = A.flatten()
print(flat)
print("View" if np.shares_memory(A, flat) else "Copy")

[10 11 12 13 14 15 16 17 18]
Copy


**Esercizio 8** 

-     creare i due  numpy array 1d
        f1= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]  
        f2= [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
-     "vederli" come matrici  4x4 ed effettuarne il prodotto scalare, memorizzando in f3 la matrice che nasce dal loro prodotto.

In [8]:
f1 = np.array([0, 1, 2, 3, 4, 5, 6, 7 , 8, 9, 10, 11, 12, 13, 14, 15])  
f2 = np.array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])
f1MatView = np.reshape(f1, (4, 4))
f2MatView = np.reshape(f2, (4, 4))
print(f1MatView)
print(f2MatView)
f3 = np.dot(f1, f2)
print(f3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
3160


**Esercizio 9**    

 Costruire:
-      Numpy Array A di shape (2,10) : array di valori random campionati da una distribuzione gaussiana con media 0 e varianza 1.
 -     Numpy array 1D B di shape (20,) formato dagli interi da 0 a 19.
 
 "Vedere" A come un array 1D di 20 elementi ed effettuare la somma di A+B



In [9]:
A = np.random.randn(2,10)
print(A)
B = np.arange(0, 20)
print(B)
viewTransformed = A.reshape((20,))
print(viewTransformed + B)

[[-0.11401316  1.63961339 -2.43166012 -1.18044584 -1.36928168 -0.00893146
  -0.89245557  2.21343171  0.98452929 -0.32684312]
 [-0.6862678  -0.73038296 -0.07573242 -0.37078825 -0.0849475  -0.96608242
   1.31360222 -0.74863965  0.22264947  1.65621923]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-0.11401316  2.63961339 -0.43166012  1.81955416  2.63071832  4.99106854
  5.10754443  9.21343171  8.98452929  8.67315688  9.3137322  10.26961704
 11.92426758 12.62921175 13.9150525  14.03391758 17.31360222 16.25136035
 18.22264947 20.65621923]


**Esercizio 10** 
-     Creare un array 2D di shape (5,5), denominato B2, con valori tutti uguali a 15.
-     Creare una copia B3 di B2. Modificare l'elemento B3[0,0] assegnandogli il valore 150. 
-     Stampare il numpy array B2 ed il numpy array B3 e verificare che B2, dopo la modifica di B3, è rimasto inalterato

In [10]:
B2 = np.full((5, 5), 15)
B3 = B2.copy()
B3[0, 0] = 150
print(B2, "\n", B3)

[[15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]] 
 [[150  15  15  15  15]
 [ 15  15  15  15  15]
 [ 15  15  15  15  15]
 [ 15  15  15  15  15]
 [ 15  15  15  15  15]]


**Esercizio 11**   

-     Costruire  un numpy array 1D, di shape (10,) denominato  f , costituito da 10 valori equidistanti nell'intervallo [0,1]
-     aumentarne la dimensionalità, in maniera tale che abbia shape (10,1)

In [11]:
f = np.linspace(0, 1, 10)
f.reshape((10, 1))
print(f)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


- **Esercizio 12**
-     Costruire i seguenti numpy array
      a= np.array([14,13,12,11])
      b=np.array([[4,3,2,1],[9,10,11,12]])

  Costruire il numpy array che si ottiene concatenando a e b per righe


In [12]:
a = np.array([[14,13,12,11]])
b = np.array([[4,3,2,1],[9,10,11,12]])
np.concatenate((b,a),axis=0)

array([[ 4,  3,  2,  1],
       [ 9, 10, 11, 12],
       [14, 13, 12, 11]])

- **Esercizio 13**
-     Costruire i seguenti numpy array
      a= np.array([14,13,12,11])
      b=np.array([[4,3,2,1],[9,10,11,12],[4,3,2,1],[9,10,11,12]])

-
- Costruire il numpy array che si ottiene concatenando a e b per colonne

In [13]:
a = np.array([[14,13,12,11]])
b = np.array([[4,3,2,1],[9,10,11,12],[4,3,2,1],[9,10,11,12]])
np.concatenate((a.T,b),axis=1)

array([[14,  4,  3,  2,  1],
       [13,  9, 10, 11, 12],
       [12,  4,  3,  2,  1],
       [11,  9, 10, 11, 12]])

**Esercizio 14**

Costruire, facendo uso di una sola riga di codice, la matrice A di ordine 10, che ha gli unici elementi diversi da zero, sulla diagonale princiaple, sulla codiagonale inferiore e sulla codiagonale superiore:

elementi diagonali $A_{i,i}=10 \quad$, i=1,20

elementi nella codiagonale inferiore $A_{i-1,i}=-12, \quad$ i=2,..,20, 

elementi nella codiagonale superiore $A_{i,i+1}=-2 \quad$ i=1,..,19

In [14]:
A = np.eye(10,10) + np.eye(10,10,k=-1) * -12 + np.eye(10,10,k=1) * -2
print(A)

[[  1.  -2.   0.   0.   0.   0.   0.   0.   0.   0.]
 [-12.   1.  -2.   0.   0.   0.   0.   0.   0.   0.]
 [  0. -12.   1.  -2.   0.   0.   0.   0.   0.   0.]
 [  0.   0. -12.   1.  -2.   0.   0.   0.   0.   0.]
 [  0.   0.   0. -12.   1.  -2.   0.   0.   0.   0.]
 [  0.   0.   0.   0. -12.   1.  -2.   0.   0.   0.]
 [  0.   0.   0.   0.   0. -12.   1.  -2.   0.   0.]
 [  0.   0.   0.   0.   0.   0. -12.   1.  -2.   0.]
 [  0.   0.   0.   0.   0.   0.   0. -12.   1.  -2.]
 [  0.   0.   0.   0.   0.   0.   0.   0. -12.   1.]]


**Esercizio 15**

Costruire la matrice identità, denominata *I*,  della stessa dimensione di *A*

In [15]:
I = np.eye(A.shape[0],A.shape[1])
print(I)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


**Esercizio 16**

Facendo uso dell'operatore slicing *:* ,costruire la matrice AA selezionando dalla matrice A le righe che vanno dalla 2 alla 9 con step 2 e le colonne che vanno dalla 3 alla 6 con step 2.
La matrice AA è una vista o una copia?


In [16]:
AA = A[2:9:2,3:6:2]
print(AA)
print("Vista" if np.shares_memory(A,AA) else "Copia")

[[ -2.   0.]
 [-12.  -2.]
 [  0. -12.]
 [  0.   0.]]
Vista


**Esercizio 17**

Facendo uso dell'operatore slicing *:*, costruire la matrice A1 selezionando dalla matrice A le colonne che vanno dalla 1 alla 5 con step 2.  Trasforma la matrice A1 in una copia.

In [17]:
A1 = A[0:10,1:5:2]
A1 = A1.copy()
print("A1 è una " + ("vista" if np.shares_memory(A,A1) else "copia"))

A1 è una copia


**Esercizio 18**

Costruisci due numpy array A e B di shape (5,5) 
   - A formata da numeri interi casuali  nell'intervallo [1,20]
   - B formata da numeri interi casuali  nell'intervallo [1,6]
 
  Costruisci con una sola riga di codice le seguenti matrici
  
  C=A+B   dove  $\quad c_{ij}=a_{ij}+b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  D=A-B   dove  $\quad d_{ij}=a_{ij}-b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  E=A*B   dove  $\quad e_{ij}=a_{ij}*b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  F=A\B   dove  $\quad f_{ij}=a_{ij}/b_{ij} \quad i=0,..,n, \quad j=0,...,n$

In [18]:
A = np.random.randint(1,21,(5,5))
B = np.random.randint(1,6,(5,5))
C = A + B
print("A = \n", A)
print("B = \n", B)
print("C = \n", C)
D = A - B
print("D = \n", D)
E = A * B
print("E = \n" , E)
F = A / B
print("F = \n" , F)

A = 
 [[12 17 18 14  5]
 [ 5 20  7 19  8]
 [17 11  9  4 19]
 [ 2 15  2 19 20]
 [ 1 17  1 14 16]]
B = 
 [[5 1 1 5 3]
 [3 2 3 3 3]
 [1 1 3 2 5]
 [4 4 3 3 1]
 [4 4 4 2 2]]
C = 
 [[17 18 19 19  8]
 [ 8 22 10 22 11]
 [18 12 12  6 24]
 [ 6 19  5 22 21]
 [ 5 21  5 16 18]]
D = 
 [[ 7 16 17  9  2]
 [ 2 18  4 16  5]
 [16 10  6  2 14]
 [-2 11 -1 16 19]
 [-3 13 -3 12 14]]
E = 
 [[60 17 18 70 15]
 [15 40 21 57 24]
 [17 11 27  8 95]
 [ 8 60  6 57 20]
 [ 4 68  4 28 32]]
F = 
 [[ 2.4        17.         18.          2.8         1.66666667]
 [ 1.66666667 10.          2.33333333  6.33333333  2.66666667]
 [17.         11.          3.          2.          3.8       ]
 [ 0.5         3.75        0.66666667  6.33333333 20.        ]
 [ 0.25        4.25        0.25        7.          8.        ]]


**Esercizio 19**

Costruisci la matrice ottenuta facendo il prodotto scalare tra le  matrici A e B (righe per colonne)

In [19]:
print(np.dot(A,B))

[[205 140 179 199 201]
 [200 160 175 172 145]
 [219 140 165 186 171]
 [213 190 190 156 120]
 [177 156 161 132 105]]


**Esercizio 20**

Costruisci l'array ottenuto sommando gli elementi delle righe della matrice B usando l'appropriata funzione di Numpy.

In [20]:
B.sum(axis=1)

array([15, 14, 12, 15, 16])

**Esercizio 21** 

Costruisci l'array ottenuto sommando gli elementi delle colonne della matrice B usando l'appropriata funzione di Numpy.

In [21]:
B.sum(axis=0)

array([17, 12, 14, 15, 14])

**Esercizio 22** 

Somma tutti gli elementi di B usando l'appropriata funzione di Numpy.

In [22]:
B.sum(axis=None)

72

**Esercizio 23**

Calcolare il minimo degli elementi di B, tra le righe, tra le colonne, il minimo di tutta la matrice B

In [23]:
print("Minimo righe:",B.min(axis=1))
print("Minimo colonne:",B.min(axis=0))
print("Minimo complessivo:",B.min(axis=None))

Minimo righe: [1 2 1 1 2]
Minimo colonne: [1 1 1 2 1]
Minimo complessivo: 1


**Esercizio 24**

Calcola e memorizza in un vettore la somma degli elementi di ogni colonna di $ |B |$. Calcola successivamente il massimo di questo vettore.
$maxsc= \max_{j=1,n} \sum_{i} |b_{ij}|$

In [24]:
print(np.max(np.sum(B, axis=0)))

17


**Esercizio 25**
Calcola, memorizzando in un vettore, la somma degli elementi di ogni riga  di $ |B |$. Calcola successivamente il massimo di questo vettore.
$maxsr= \max_{i=1,n} \sum_{j} |b_{ij}|$

In [25]:
print(np.max(np.sum(B, axis=1)))

16


**Esercizio 26**

Effettua nella matrice B lo scambio tra la  riga 2 e  la riga 3

**Esercizio 27**

Calcola il valore massimo della colonna 0-esima della matrice B e l'indice di riga a cui appartiene

In [26]:
max = np.max(B[0])
print(max)
print(np.where(max))

5
(array([0], dtype=int64),)


**Esercizio 28**   


Scrivi una funzione border(m,n,visualizza=False) che:
-      crea un array 2D di shape(m,n) che abbia tutti valori nulli
-     imposta ad 1  i valori degli elementi sul bordo dell'array (prima ed ultima riga, prima e l'ultima colonna)
-      Preveda un argomento di default che se impostato a True visualizza la matrice

In [27]:
def border(m, n, visualizza=False):
    arr = np.zeros((m, n))
    arr[0] = 1
    arr[-1] = 1
    arr[0:m, -1] = 1
    arr[0:m, 0] = 1
    if visualizza:
        print(arr)


border(4, 15, visualizza=True)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**Esercizio 29**

Scrivi una funzione `visualizza(f,a,b)`che prende in input una lambda function f, gli estremi dell'intervallo [a,b] su cui è definita e la visualizzi in una finestra grafica

Chaima la funzione passandogli la funzione f(x)=sin(2*$\pi$*x), [a,b]=[0,2*$\pi$]

**Esercizio 30**

Scrivi una funzione `visualizza2(f,a,b,f2,a2,b2)`che prende in input una lambda function f e gli estremi dell'intervallo [a,b]  su cui è definita, una lambda function f2 e gli estremi dell'intervallo su cui è definita [a2,b2] e le visualizzi sulla stessa finestra grafica.

Chaima la funzione passandogli  una funzione f(x) quadratica ed una funzione f2(x) exponenziale ed [a,b]=[0,2]