# Esercizio 1

Definire i  numpy array a=[1.2, 5.4, 6, 1.59] e b=[5.2, 1.2, 1.5, 2] ed eseguire le seguenti operazioni:
  - calcolare la radice quadrata degli elementi di a;
   - calcolare 𝑒xp(𝑎/2) ;
   - calcolare il vettore somma tra a e b ;
   - moltiplicare ogni elemento di a per il corrispondente elemento di b;
   - creare un vettore di valori uniformemente equispaziati tra 0 e 30 con passo  0.5;
   - creare un vettore di 100 valori uniformemente equispaziati tra 1 e 2.
   - usare linspace() per creare un numpy array 2x6 con prima riga di 6 valori uniformi compresi tra 10 e 20 e seconda riga 6 valori     
      uniformi compresi tra  20 e 10;
   - calcolare il prodotto scalare tra a e b;
   - creare la matrice A che ha come righe i vettori a e b ;
   - calcolare il prodotto scalare tra i due vettori a e b;
   - eseguire il prodotto della matrice A per il vettore b e assegnarlo ad y;
   - costruire una matrice diagonale D a partire dal vettore a;

In [1]:
import numpy as np
a = np.array([1.2, 5.4, 6, 1.59])
b = np.array([5.2, 1.2, 1.5, 2])
print(np.square(a))
print(np.exp(a / 2))
print(np.add(a, b))
print(np.multiply(a, b))
print(np.arange(0, 30, 0.5), "oppure", np.linspace(0, 30, 60, endpoint=False))
print(np.linspace(1, 2, 100))
print(np.array([np.linspace(10, 20, 6), np.linspace(20, 10, 6)]))
print(np.dot(a, b))
A = np.array([a, b])
print(A)
y = A * b
print(y)
D = np.diag(a)
print(D)

[ 1.44   29.16   36.      2.5281]
[ 1.8221188  14.87973172 20.08553692  2.214441  ]
[6.4  6.6  7.5  3.59]
[6.24 6.48 9.   3.18]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5
 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5] oppure [ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5
 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5]
[1.         1.01010101 1.02020202 1.03030303 1.04040404 1.05050505
 1.06060606 1.07070707 1.08080808 1.09090909 1.1010101  1.11111111
 1.12121212 1.13131313 1.14141414 1.15151515 1.16161616 1.17171717
 1.18181818 1.19191919 1.2020202  1.21212121 1.22222

# Esercizio 2

Costruire  i seguenti Numpy array 2d utilizzando il minor numero di istruzioni possibili

<img src="ese2.png" width="500">

In [2]:
A = np.full((3, 4), 2)
A[0:3, 3] = 3
print(A)
B = np.zeros((3, 13))
B[0:3, 0:3] = np.eye(3) * 2
B[0:3, 3:13] = np.array([np.arange(1, 11)])
print(B)
C = np.eye(5,5) * 2
C += np.eye(5, k=1) * -1
C += np.eye(5, k=-1) * -1
print(C)
D = np.zeros((6,4))
D[0:2] = np.array([np.repeat(2,4), np.repeat(3,4)])
print(D)

[[2 2 2 3]
 [2 2 2 3]
 [2 2 2 3]]
[[ 2.  0.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 0.  2.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 0.  0.  2.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]]
[[ 2. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1.  2.]]
[[2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Esercizio 3

Calcolare la somma dei primi n numeri naturali dispari sia utilizzando un ciclo for che servendosi dell'istruzione sum di numpy.

In [3]:
n = 5
arr = np.array([])
cnt = 0
numerazione = 1
somma = 0
while cnt < n:
    cnt = cnt + 1
    somma += numerazione
    arr = np.append(arr,numerazione)
    numerazione += 2
print(somma)
print(arr, np.sum(arr))

25
[1. 3. 5. 7. 9.] 25.0


# Esercizo 4

Scrivere una function Python per generare l'n-esimo termine (n > 2) della successione
di Fibonacci. Scrivere poi una function ricorsiva che risolva lo stesso problema
e confrontare i tempi di calcolo delle due functions per n = 24.

Ricordiamo la formula per generare i i numeri di Fibonacci:

$$F_0=1$$
$$F_1=1$$
$$F_n = F_{n-1} + F_{n-2}, \quad n=2,...$$

In [4]:
from time import perf_counter

t1 = perf_counter()
def fib(n):
    if n > 1:
        return fib(n - 1) + fib(n - 2)
    else: 
        return 1
t2 = perf_counter()
print("Elapsed: ", t2 - t1)

fib(11)

Elapsed:  0.0001847000021371059


144